import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Login {

	WebDriver driver;
	WebElement txtUser;
	WebElement txtPassword;
	WebElement btnLogin;
	WebElement message;

	// Constructor
	public Login(WebDriver driverA) {

		this.driver = driverA;

	}

	public void initSession(String user, String password) {

		txtUser = driver.findElement(By.name("user"));
		txtUser.sendKeys(user);
		txtPassword = driver.findElement(By.name("password"));
		txtPassword.sendKeys(password);
		btnLogin = driver.findElement(By.xpath("/html/body/center/div/form/table/tbody/tr[3]/td[2]/input"));
		btnLogin.click();

	}

	public boolean validateSession() {
		
		boolean validation = true;
		try {
		message = driver.findElement(By.id("errorMessage"));

		if (message.isDisplayed()) {
			validation = false;
		}
		
		}catch (Exception a) {
			System.out.print(a.getMessage());
		}
		
		return validation;
	}
}